### ISSUE TITLE
Responsive issue

### ISSUE THREAD

**Issue by zallek** [botify-hq/developers-docs#99]
<img width="419" alt="screen shot 2016-03-30 at 00 22 57" src="https://cloud.githubusercontent.com/assets/1886834/14125848/aaf9954e-f60d-11e5-894b-a84b8f3296be.png">

Add on inlined code:
```SCSS
code {
  word-break: break-all;
  word-wrap: break-word;
}
```

FInd a way to better position Edit button. as:
```SCSS
.edit-page-button {
  position: relative;
  // no float

  a {
    position: absolute;
    right: 0;
    top: -25px;
  }
}
```
